//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiMeter.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiMeter.UI.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds.
        /// </summary>
        internal static string BuildItemsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("BuildItemsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular References.
        /// </summary>
        internal static string CircularReferenceViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CircularReferenceViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Errors.
        /// </summary>
        internal static string CodeErrorGraphViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CodeErrorGraphViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Review.
        /// </summary>
        internal static string CodeReviewViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CodeReviewViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges.
        /// </summary>
        internal static string EdgesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("EdgesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Graph.
        /// </summary>
        internal static string GraphViewModel_DisplayName {
            get {
                return ResourceManager.GetString("GraphViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewBuilds {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular References.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewCircularReferences {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewCircularReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewDependencies {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Graph.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewDependencyGraph {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewDependencyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements Graph.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewRequirementsGraph {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewRequirementsGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArchiMeter.
        /// </summary>
        internal static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements Graph.
        /// </summary>
        internal static string RequirementGraphViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RequirementGraphViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure.
        /// </summary>
        internal static string Structure {
            get {
                return ResourceManager.GetString("Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Errors.
        /// </summary>
        internal static string TestErrorGraphViewModel_DisplayName {
            get {
                return ResourceManager.GetString("TestErrorGraphViewModel_DisplayName", resourceCulture);
            }
        }
    }
}
