//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiMetrics.UI.Localization
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Strings
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiMetrics.UI.Localization.Strings", typeof(Strings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to About.
		/// </summary>
		internal static string About
		{
			get
			{
				return ResourceManager.GetString("About", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Afferent Coupling.
		/// </summary>
		internal static string AfferentCoupling
		{
			get
			{
				return ResourceManager.GetString("AfferentCoupling", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ArchiMetrics.
		/// </summary>
		internal static string AppTitle
		{
			get
			{
				return ResourceManager.GetString("AppTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Average Complexity: {0},.
		/// </summary>
		internal static string AverageComplexityFormat
		{
			get
			{
				return ResourceManager.GetString("AverageComplexityFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lines of code which are counted as broken: {0}..
		/// </summary>
		internal static string BrokenLocFormat
		{
			get
			{
				return ResourceManager.GetString("BrokenLocFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to By Impact Level.
		/// </summary>
		internal static string ByImpactLevel
		{
			get
			{
				return ResourceManager.GetString("ByImpactLevel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to By Kind.
		/// </summary>
		internal static string ByKind
		{
			get
			{
				return ResourceManager.GetString("ByKind", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to By Quality Attribute.
		/// </summary>
		internal static string ByQualityAttribute
		{
			get
			{
				return ResourceManager.GetString("ByQualityAttribute", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Charts.
		/// </summary>
		internal static string Charts
		{
			get
			{
				return ResourceManager.GetString("Charts", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Code Metrics.
		/// </summary>
		internal static string CodeMetrics
		{
			get
			{
				return ResourceManager.GetString("CodeMetrics", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Code Review.
		/// </summary>
		internal static string CodeReview
		{
			get
			{
				return ResourceManager.GetString("CodeReview", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Comment.
		/// </summary>
		internal static string Comment
		{
			get
			{
				return ResourceManager.GetString("Comment", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Complexity.
		/// </summary>
		internal static string Complexity
		{
			get
			{
				return ResourceManager.GetString("Complexity", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Copyright: Reimers.dk.
		/// </summary>
		internal static string Copyright
		{
			get
			{
				return ResourceManager.GetString("Copyright", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Coupling.
		/// </summary>
		internal static string Coupling
		{
			get
			{
				return ResourceManager.GetString("Coupling", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create.
		/// </summary>
		internal static string Create
		{
			get
			{
				return ResourceManager.GetString("Create", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create:.
		/// </summary>
		internal static string CreateColon
		{
			get
			{
				return ResourceManager.GetString("CreateColon", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cyclomatic Complexity.
		/// </summary>
		internal static string CyclomaticComplexity
		{
			get
			{
				return ResourceManager.GetString("CyclomaticComplexity", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cyclomatic Complexity: {0}.
		/// </summary>
		internal static string CyclomaticComplexityFormat
		{
			get
			{
				return ResourceManager.GetString("CyclomaticComplexityFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Define.
		/// </summary>
		internal static string Define
		{
			get
			{
				return ResourceManager.GetString("Define", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete.
		/// </summary>
		internal static string Delete
		{
			get
			{
				return ResourceManager.GetString("Delete", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Depth of Inheritance.
		/// </summary>
		internal static string DepthOfInheritance
		{
			get
			{
				return ResourceManager.GetString("DepthOfInheritance", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Edges.
		/// </summary>
		internal static string Edges
		{
			get
			{
				return ResourceManager.GetString("Edges", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error.
		/// </summary>
		internal static string Error
		{
			get
			{
				return ResourceManager.GetString("Error", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Errors Found.
		/// </summary>
		internal static string ErrorsFound
		{
			get
			{
				return ResourceManager.GetString("ErrorsFound", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {}{0} errors found.
		/// </summary>
		internal static string ErrorsFoundFormat
		{
			get
			{
				return ResourceManager.GetString("ErrorsFoundFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Failed.
		/// </summary>
		internal static string Failed
		{
			get
			{
				return ResourceManager.GetString("Failed", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to File.
		/// </summary>
		internal static string File
		{
			get
			{
				return ResourceManager.GetString("File", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Finding.
		/// </summary>
		internal static string Finding
		{
			get
			{
				return ResourceManager.GetString("Finding", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to General.
		/// </summary>
		internal static string General
		{
			get
			{
				return ResourceManager.GetString("General", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Graph.
		/// </summary>
		internal static string Graph
		{
			get
			{
				return ResourceManager.GetString("Graph", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Impact Level.
		/// </summary>
		internal static string ImpactLevel
		{
			get
			{
				return ResourceManager.GetString("ImpactLevel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to in {0} files..
		/// </summary>
		internal static string InFilesFormat
		{
			get
			{
				return ResourceManager.GetString("InFilesFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Installed Programs:.
		/// </summary>
		internal static string InstalledPrograms
		{
			get
			{
				return ResourceManager.GetString("InstalledPrograms", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Kind.
		/// </summary>
		internal static string Kind
		{
			get
			{
				return ResourceManager.GetString("Kind", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Warning: This computer program is protected by copyright law and international treaties. Unauthorized use, reproduction or distribution of this program, or any portion of it, may result in severe criminal penalties, and will be prosecuted to the maximum extent possible under the law..
		/// </summary>
		internal static string LegalWarning
		{
			get
			{
				return ResourceManager.GetString("LegalWarning", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to List.
		/// </summary>
		internal static string List
		{
			get
			{
				return ResourceManager.GetString("List", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Load Model.
		/// </summary>
		internal static string LoadModel
		{
			get
			{
				return ResourceManager.GetString("LoadModel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Load Patterns.
		/// </summary>
		internal static string LoadPatterns
		{
			get
			{
				return ResourceManager.GetString("LoadPatterns", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Load Rules.
		/// </summary>
		internal static string LoadRules
		{
			get
			{
				return ResourceManager.GetString("LoadRules", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lines of Code.
		/// </summary>
		internal static string LoC
		{
			get
			{
				return ResourceManager.GetString("LoC", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lines of Code: {0}.
		/// </summary>
		internal static string LocFormat
		{
			get
			{
				return ResourceManager.GetString("LocFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Maintainability.
		/// </summary>
		internal static string Maintainability
		{
			get
			{
				return ResourceManager.GetString("Maintainability", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Maintainability Index.
		/// </summary>
		internal static string MaintainabilityIndex
		{
			get
			{
				return ResourceManager.GetString("MaintainabilityIndex", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Maintainability Index: {0:n2}.
		/// </summary>
		internal static string MaintainabilityIndexFormat
		{
			get
			{
				return ResourceManager.GetString("MaintainabilityIndexFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Max Depth of Inheritance {0},.
		/// </summary>
		internal static string MaxDepthOfInheritanceFormat
		{
			get
			{
				return ResourceManager.GetString("MaxDepthOfInheritanceFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Max Namespace Depth.
		/// </summary>
		internal static string MaxNamespaceDepth
		{
			get
			{
				return ResourceManager.GetString("MaxNamespaceDepth", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Members.
		/// </summary>
		internal static string Members
		{
			get
			{
				return ResourceManager.GetString("Members", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Metrics.
		/// </summary>
		internal static string Metrics
		{
			get
			{
				return ResourceManager.GetString("Metrics", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		internal static string Name
		{
			get
			{
				return ResourceManager.GetString("Name", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Namespace.
		/// </summary>
		internal static string Namespace
		{
			get
			{
				return ResourceManager.GetString("Namespace", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New Vertex.
		/// </summary>
		internal static string NewVertex
		{
			get
			{
				return ResourceManager.GetString("NewVertex", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Passed.
		/// </summary>
		internal static string Passed
		{
			get
			{
				return ResourceManager.GetString("Passed", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Pattern.
		/// </summary>
		internal static string Pattern
		{
			get
			{
				return ResourceManager.GetString("Pattern", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Percent of code in group.
		/// </summary>
		internal static string PercentOfCodeInGroup
		{
			get
			{
				return ResourceManager.GetString("PercentOfCodeInGroup", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Print Report.
		/// </summary>
		internal static string PrintReport
		{
			get
			{
				return ResourceManager.GetString("PrintReport", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Project.
		/// </summary>
		internal static string Project
		{
			get
			{
				return ResourceManager.GetString("Project", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Projects.
		/// </summary>
		internal static string Projects
		{
			get
			{
				return ResourceManager.GetString("Projects", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Quality Attribute.
		/// </summary>
		internal static string QualityAttribute
		{
			get
			{
				return ResourceManager.GetString("QualityAttribute", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Relational Cohesion.
		/// </summary>
		internal static string RelationalCohesion
		{
			get
			{
				return ResourceManager.GetString("RelationalCohesion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Results.
		/// </summary>
		internal static string Results
		{
			get
			{
				return ResourceManager.GetString("Results", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Review.
		/// </summary>
		internal static string Review
		{
			get
			{
				return ResourceManager.GetString("Review", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reviewed Rules.
		/// </summary>
		internal static string ReviewedRules
		{
			get
			{
				return ResourceManager.GetString("ReviewedRules", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Rules.
		/// </summary>
		internal static string Rules
		{
			get
			{
				return ResourceManager.GetString("Rules", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save Model.
		/// </summary>
		internal static string SaveModel
		{
			get
			{
				return ResourceManager.GetString("SaveModel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save Patterns.
		/// </summary>
		internal static string SavePatterns
		{
			get
			{
				return ResourceManager.GetString("SavePatterns", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save Rules.
		/// </summary>
		internal static string SaveRules
		{
			get
			{
				return ResourceManager.GetString("SaveRules", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Set Path.
		/// </summary>
		internal static string SetPath
		{
			get
			{
				return ResourceManager.GetString("SetPath", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Setting.
		/// </summary>
		internal static string Setting
		{
			get
			{
				return ResourceManager.GetString("Setting", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Settings.
		/// </summary>
		internal static string Settings
		{
			get
			{
				return ResourceManager.GetString("Settings", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Snippet.
		/// </summary>
		internal static string Snippet
		{
			get
			{
				return ResourceManager.GetString("Snippet", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Source.
		/// </summary>
		internal static string Source
		{
			get
			{
				return ResourceManager.GetString("Source", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spelling.
		/// </summary>
		internal static string Spelling
		{
			get
			{
				return ResourceManager.GetString("Spelling", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Structures.
		/// </summary>
		internal static string Structures
		{
			get
			{
				return ResourceManager.GetString("Structures", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Target.
		/// </summary>
		internal static string Target
		{
			get
			{
				return ResourceManager.GetString("Target", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Total Lines of Code: {0},.
		/// </summary>
		internal static string TotalLocFormat
		{
			get
			{
				return ResourceManager.GetString("TotalLocFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Transform.
		/// </summary>
		internal static string Transform
		{
			get
			{
				return ResourceManager.GetString("Transform", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Type Kind.
		/// </summary>
		internal static string TypeKind
		{
			get
			{
				return ResourceManager.GetString("TypeKind", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Type Name.
		/// </summary>
		internal static string TypeName
		{
			get
			{
				return ResourceManager.GetString("TypeName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Types.
		/// </summary>
		internal static string Types
		{
			get
			{
				return ResourceManager.GetString("Types", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to _Path:.
		/// </summary>
		internal static string UnderscorePathColon
		{
			get
			{
				return ResourceManager.GetString("UnderscorePathColon", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		internal static string Update
		{
			get
			{
				return ResourceManager.GetString("Update", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Validation.
		/// </summary>
		internal static string Validation
		{
			get
			{
				return ResourceManager.GetString("Validation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Vertex.
		/// </summary>
		internal static string Vertex
		{
			get
			{
				return ResourceManager.GetString("Vertex", resourceCulture);
			}
		}
	}
}
