//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiMetrics.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiMetrics.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArchiMetrics.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Kind.
        /// </summary>
        public static string ByKind {
            get {
                return ResourceManager.GetString("ByKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright: Reimers.dk.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define.
        /// </summary>
        public static string Define {
            get {
                return ResourceManager.GetString("Define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Found.
        /// </summary>
        public static string ErrorsFound {
            get {
                return ResourceManager.GetString("ErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding.
        /// </summary>
        public static string Finding {
            get {
                return ResourceManager.GetString("Finding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Programs:.
        /// </summary>
        public static string InstalledPrograms {
            get {
                return ResourceManager.GetString("InstalledPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This computer program is protected by copyright law and international treaties. Unauthorized use, reproduction or distribution of this program, or any portion of it, may result in severe criminal penalties, and will be prosecuted to the maximum extent possible under the law..
        /// </summary>
        public static string LegalWarning {
            get {
                return ResourceManager.GetString("LegalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of Code.
        /// </summary>
        public static string LoC {
            get {
                return ResourceManager.GetString("LoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Report.
        /// </summary>
        public static string PrintReport {
            get {
                return ResourceManager.GetString("PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Attribute.
        /// </summary>
        public static string QualityAttribute {
            get {
                return ResourceManager.GetString("QualityAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet.
        /// </summary>
        public static string Snippet {
            get {
                return ResourceManager.GetString("Snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling.
        /// </summary>
        public static string Spelling {
            get {
                return ResourceManager.GetString("Spelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        public static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Kind.
        /// </summary>
        public static string TypeKind {
            get {
                return ResourceManager.GetString("TypeKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
    }
}
